/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorRequerimientos;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import modelo.VO.*;
import controlador.ControladorRequerimientos;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
/**
 *
 * @author Yinet
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private static final ControladorRequerimientos controlador = new ControladorRequerimientos();
    private VentanaResultadoC1 ventanaResultadosC1;
    private VentanaResultadoC2 ventanaResultadosC2;    
    private VentanaResultadoC3 ventanaResultadosC3;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
  
        initComponents();
        // inicializa la ventana de las consultas
        ventanaResultadosC1 = new VentanaResultadoC1();
        ventanaResultadosC1.setVisible(false);
        ventanaResultadosC2 = new VentanaResultadoC2();
        ventanaResultadosC2.setVisible(false);
        ventanaResultadosC3 = new VentanaResultadoC3();
        ventanaResultadosC3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        BotonC3 = new javax.swing.JPanel();
        LabelC3 = new javax.swing.JLabel();
        BotonC2 = new javax.swing.JPanel();
        LabelC1 = new javax.swing.JLabel();
        BotonC1 = new javax.swing.JPanel();
        LabelC2 = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonC3.setBackground(new java.awt.Color(153, 181, 202));
        BotonC3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonC3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonC3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonC3MouseExited(evt);
            }
        });

        LabelC3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        LabelC3.setText("CONSULTA 3 ");

        javax.swing.GroupLayout BotonC3Layout = new javax.swing.GroupLayout(BotonC3);
        BotonC3.setLayout(BotonC3Layout);
        BotonC3Layout.setHorizontalGroup(
            BotonC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonC3Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(LabelC3)
                .addGap(43, 43, 43))
        );
        BotonC3Layout.setVerticalGroup(
            BotonC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonC3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelC3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        fondo.add(BotonC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 250, 60));

        BotonC2.setBackground(new java.awt.Color(153, 181, 202));
        BotonC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonC2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonC2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonC2MouseExited(evt);
            }
        });

        LabelC1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        LabelC1.setText("CONSULTA 2 ");

        javax.swing.GroupLayout BotonC2Layout = new javax.swing.GroupLayout(BotonC2);
        BotonC2.setLayout(BotonC2Layout);
        BotonC2Layout.setHorizontalGroup(
            BotonC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonC2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(LabelC1)
                .addGap(43, 43, 43))
        );
        BotonC2Layout.setVerticalGroup(
            BotonC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonC2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelC1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        fondo.add(BotonC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 250, 60));

        BotonC1.setBackground(new java.awt.Color(153, 181, 202));
        BotonC1.setToolTipText("");
        BotonC1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonC1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonC1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonC1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonC1MouseExited(evt);
            }
        });

        LabelC2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        LabelC2.setText("CONSULTA 1 ");

        javax.swing.GroupLayout BotonC1Layout = new javax.swing.GroupLayout(BotonC1);
        BotonC1.setLayout(BotonC1Layout);
        BotonC1Layout.setHorizontalGroup(
            BotonC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonC1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(LabelC2)
                .addGap(37, 37, 37))
        );
        BotonC1Layout.setVerticalGroup(
            BotonC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonC1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(LabelC2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        fondo.add(BotonC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 250, 60));

        BACK.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yinet\\OneDrive\\Público\\Documentos2\\NetBeansProjects\\mavenproject1\\src\\main\\java\\Resources\\fondoR5.png")); // NOI18N
        BACK.setText("BACK");
        fondo.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonC1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonC1MouseEntered
        // TODO add your handling code here:
        BotonC1.setBackground(Color.gray);
    }//GEN-LAST:event_BotonC1MouseEntered

    private void BotonC1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonC1MouseExited
        // TODO add your handling code here:
        BotonC1.setBackground(new Color(153,181,202));
    }//GEN-LAST:event_BotonC1MouseExited

    private void BotonC2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonC2MouseEntered
        // TODO add your handling code here:
        BotonC2.setBackground(Color.gray);
    }//GEN-LAST:event_BotonC2MouseEntered

    private void BotonC3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonC3MouseEntered
        // TODO add your handling code here:
        BotonC3.setBackground(Color.gray);
    }//GEN-LAST:event_BotonC3MouseEntered

    private void BotonC3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonC3MouseExited
        // TODO add your handling code here:
        BotonC3.setBackground(new Color(153,181,202));
    }//GEN-LAST:event_BotonC3MouseExited

    private void BotonC2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonC2MouseExited
        // TODO add your handling code here:
        BotonC2.setBackground(new Color(153,181,202));
    }//GEN-LAST:event_BotonC2MouseExited

    private void BotonC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonC1MouseClicked
        // TODO add your handling code here:
        ventanaResultadosC1.setVisible(true);
        
    }//GEN-LAST:event_BotonC1MouseClicked

    private void BotonC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonC2MouseClicked
        // TODO add your handling code here:
        ventanaResultadosC2.setVisible(true);
    }//GEN-LAST:event_BotonC2MouseClicked

    private void BotonC3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonC3MouseClicked
        // TODO add your handling code here:
        ventanaResultadosC3.setVisible(true);
    }//GEN-LAST:event_BotonC3MouseClicked
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JPanel BotonC1;
    private javax.swing.JPanel BotonC2;
    private javax.swing.JPanel BotonC3;
    private javax.swing.JLabel LabelC1;
    private javax.swing.JLabel LabelC2;
    private javax.swing.JLabel LabelC3;
    private javax.swing.JPanel fondo;
    // End of variables declaration//GEN-END:variables
}
